### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Shalopay** [Shalopay/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by ShalopayShadow** [comment]
Experience
-	administration
Since 2017 the president of the Chinese Basketball Association (CBA)
Since 2016 an owner of the winery called Yao Family Wines
Since 2009 president and owner of the CBA’s Shanghai Sharks basketball team
-	sports
2002 –2011 played in the NBA basketball team Houston Rockets
2006 took part in the World Championship
2000, 2004, 2008 took part in the Olympic Games as a member of the Chinese Olympic Basketball Team
1997 – 2002 member of Shanghai Sharks, basketball team in CBA

**Comment by Shalopay** [comment]
to be honestly I expected more
